openapi: 3.0.3
info:
  description: This API receives weather sensor readings from weather stations around the world
  version: "1.0.0"
  title: Weather API
  contact:
    email: mmulder10@bcit.ca
paths:
  /weather/temperature:
    post:
      summary: Reports a batch of temperature sensor readings
      operationId: app.report_temperature_readings
      description: Adds a batch of temperature readings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureReadingBatch'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'
    
  /weather/precipitation:
    post:
      summary: Reports a batch of precipitation readings
      operationId: app.report_precipitation_reading
      description: Adds a batch of temperature readings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrecipitationReadingBatch'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'

components:
  schemas:
    TemperatureReadingBatch:
      required:
      - station_id
      - station_name
      - reporting_timestamp
      - readings
      properties:
        station_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        station_name:
          type: string
          example: "Yellowknife North"
        reporting_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        readings:
          type: array
          items:
            $ref: '#/components/schemas/TemperatureReading'
      type: object

    TemperatureReading:
      required:
        - temperature_celsius
        - recorded_timestamp
      properties:
        temperature_celsius:
          type: number
          example: -13.2
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
      type: object

    PrecipitationReadingBatch:
      required:
      - station_id
      - station_name
      - reporting_timestamp
      - readings
      properties:
        station_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        station_name:
          type: string
          example: "Yellowknife North"
        reporting_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        readings:
          type: array
          items:
            $ref: '#/components/schemas/PrecipitationReading'
      type: object

    PrecipitationReading:
      required:
        - precipitation_mm
        - precip_type
        - recorded_timestamp
      properties:
        precipitation_mm:
          type: number
          example: 2.3
        precip_type:
          type: string
          description: the type of precipition
          enum:
            - none
            - rain
            - snow
            - hail
            - other
          example: hail
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
      type: object
